// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaznafleyywurqjlkpcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlhem5hZmxleXl3dXJxamxrcGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDg5NzgsImV4cCI6MjA2NTQ4NDk3OH0.bauOfTwT05S8geSZMVm9R6H44bh6lUYkzjo3LZVSHGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);